# Task 11

In [ ]:
import pickle

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

In [ ]:
datafr

               Collections           Sales     Buyers        Txns     Owners
0            Axie Infinity  $4,090,222,023  1,790,587  17,670,824  2,130,467
1     Bored Ape Yacht Club  $2,439,754,017     12,052      32,670      6,586
2              CryptoPunks  $2,388,467,992      6,076      22,269      3,804
3    Mutant Ape Yacht Club  $1,744,822,678     23,768      51,775     13,121
4               Art Blocks  $1,310,734,558     33,549     184,470     36,091
..                     ...             ...        ...         ...        ...
245             Mindblowon     $21,255,015     11,313      16,333      3,973
246        Sipherian Surge     $21,053,426      6,210      15,023      3,636
247            Gutter Rats     $20,915,001      2,931       5,209        NaN
248             Wool Pouch     $20,911,179      2,249       6,139      3,270
249            Los Muertos     $20,901,871     11,143      25,406      4,328

[250 rows x 5 columns]

In [ ]:
datafr.drop('Txns', axis=1)

               Collections           Sales     Buyers     Owners
0            Axie Infinity  $4,090,222,023  1,790,587  2,130,467
1     Bored Ape Yacht Club  $2,439,754,017     12,052      6,586
2              CryptoPunks  $2,388,467,992      6,076      3,804
3    Mutant Ape Yacht Club  $1,744,822,678     23,768     13,121
4               Art Blocks  $1,310,734,558     33,549     36,091
..                     ...             ...        ...        ...
245             Mindblowon     $21,255,015     11,313      3,973
246        Sipherian Surge     $21,053,426      6,210      3,636
247            Gutter Rats     $20,915,001      2,931        NaN
248             Wool Pouch     $20,911,179      2,249      3,270
249            Los Muertos     $20,901,871     11,143      4,328

[250 rows x 4 columns]

In [ ]:
datafr.fillna(0,axis=1)

In [ ]:
datafr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Collections  250 non-null    object
 1   Sales        250 non-null    object
 2   Buyers       250 non-null    object
 3   Txns         250 non-null    object
 4   Owners       231 non-null    object
dtypes: object(5)
memory usage: 9.9+ KB

In [ ]:
columns= ["Sales", 'Txns', 'Owners']
for i in columns:
  datafr[i]=datafr[i].str.replace('[$,]','',regex=True)
  datafr[i]=pd.to_numeric(datafr[i])

In [ ]:
datafr['Buyers']=datafr['Buyers'].str.replace(',','',regex=True)

datafr['Buyers'] = pd.to_numeric(datafr['Buyers'], errors='coerce')

In [ ]:
print(datafr.head(2))
datafr.dtypes

   Collections       Sales   Buyers      Txns     Owners
0           21  4090222023  1790587  17670824  2130467.0
1           32  2439754017    12052     32670     6586.0

Collections      int64
Sales            int64
Buyers           int64
Txns             int64
Owners         float64
dtype: object

In [ ]:
encoder= LabelEncoder()
datafr["Collections"] = encoder.fit_transform(datafr['Collections'])

In [ ]:
datafr.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Collections  250 non-null    int64
 1   Sales        250 non-null    int64
 2   Buyers       250 non-null    int64
 3   Txns         250 non-null    int64
 4   Owners       231 non-null    float64
dtypes: float64(1), int64(4)
memory usage: 9.9 KB

In [ ]:
datafr.to_csv(r'encoded-data.csv', index = False, header = True)

# Train-Test Split

In [ ]:
x=datafr.drop(columns=['Owners'])
y=datafr['Owners']

In [ ]:
x.head()

   Collections       Sales   Buyers      Txns
0           21  4090222023  1790587  17670824
1           32  2439754017    12052     32670
2           59  2388467992     6076     22269
3          150  1744822678    23768     51775
4           18  1310734558    33549    184470

In [ ]:
y

0      2.130467e+06
1      6.586000e+03
2      3.804000e+03
3      1.312100e+04
4      3.609100e+04
           ...
245    3.973000e+03
246    3.636000e+03
247    3.911334e+04
248    3.270000e+03
249    4.328000e+03
Name: Owners, Length: 250, dtype: float64

In [ ]:
train_x, test_x, train_y, test_y = train_test_split(x,y, test_size=0.2, random_state=42)

In [ ]:
train_x.shape

(200, 4)

In [ ]:
test_x.shape

(50, 4)

In [ ]:
train_y.shape

(200,)

In [ ]:
test_y.shape

(50,)

# Applying Classifiers

In [ ]:
modelsvc=SVC()
modelsvc.fit(train_x,train_y)

In [ ]:
y_pred = modelsvc.predict(test_x)
accuracy = accuracy_score(test_y, y_pred)
print("Accuracy:", accuracy*100)

Accuracy: 18.0